contao/core-bundle

composer.json, src/Command/AutomatorCommand.php, tests/Command/AutomatorCommandTest.php, tests/bootstrap.php
* Using the question instead of the deprecated dialog helper
* Fixed a few bugs
* Added unit tests
=> Fixed AutomatorCommand

autoload.json, composer.json, contao/bootstrap.php, contao/controllers/FrontendIndex.php, contao/library/Contao/Controller.php, contao/library/Contao/Template.php, src/ContaoCoreBundle.php, src/Controller/BackendController.php, src/Controller/FrontendController.php, src/EventListener/ContainerScopeListener.php, src/EventListener/LegacyScriptListener.php, src/Resources/config/routing.yml, src/Resources/config/services.yml, src/Routing/FrontendLoader.php
=> Use Symfony routing

contao/classes/Backend.php, contao/classes/Frontend.php, contao/config/default.php, contao/dca/tl_article.php, contao/dca/tl_settings.php, contao/elements/ContentDownload.php, contao/elements/ContentDownloads.php, contao/elements/ContentTeaser.php, contao/languages/en/tl_settings.xlf, contao/library/Contao/Controller.php, contao/library/Contao/InsertTags.php, contao/modules/ModuleArticle.php, contao/modules/ModuleArticlenav.php, contao/modules/ModuleBreadcrumb.php, contao/modules/ModulePassword.php, contao/modules/ModuleRegistration.php, contao/modules/ModuleSearch.php, contao/pages/PageForward.php, contao/templates/modules/mod_search_advanced.html5, contao/templates/modules/mod_search_simple.html5
See https://github.com/contao/contao/issues/40
=> Remove disableAlias

contao/classes/BackendUser.php, contao/classes/FrontendUser.php
Finally fixes https://github.com/contao/core/issues/2236
=> Use shutdown function instead of destruct

contao/classes/BackendUser.php, contao/controllers/BackendPreview.php, contao/controllers/BackendSwitch.php, contao/templates/backend/be_preview.html5
Fixes:
- backend access attempt when not logged in
- preview bar
=> Routing fixes

contao/classes/Frontend.php, contao/library/Contao/Controller.php, src/Resources/config/services.yml, src/Routing/FrontendLoader.php, tests/Routing/FrontendLoaderTest.php
This is the PR for contao/contao#62. @contao/developers Please review.
=> Unify the front end routes (see contao/contao#62)

contao/classes/BackendUser.php, contao/classes/Frontend.php, contao/controllers/BackendPreview.php, contao/library/Contao/Template.php, contao/templates/backend/be_confirm.html5, contao/templates/backend/be_install.html5, contao/templates/backend/be_login.html5, contao/templates/backend/be_main.html5, contao/templates/backend/be_welcome.html5, contao/templates/modules/mod_article.html5
This is the follow-up PR to #53 as discussed yesterday. @contao/developers Please review.
=> Add the Template::route() method and replace all hardcoded template routes

src/EventListener/InitializeSystemListener.php
Now that the Contao system is initialized after routing we can match the route name.
=> Use route name and request path when initializing system

src/EventListener/ToggleViewListener.php, tests/EventListener/ToggleViewListenerTest.php
see https://github.com/contao/contao/issues/46
=> ToggleView cookie path

src/Analyzer/HtaccessAnalyzer.php, src/Command/AutomatorCommand.php, src/HttpKernel/Bundle/ContaoModuleBundle.php, src/Security/ContaoAuthenticator.php
Most of the code actually was already `private` :)
=> Make private what does not need to be overridden

src/EventListener/InitializeSystemListener.php, src/Resources/contao/languages/en/exception.xlf
=> [RTM] Insecure document root is allowed for localhost

src/Resources/contao/controllers/BackendInstall.php, src/Resources/contao/library/Contao/Config.php, src/Resources/contao/library/Contao/Encryption.php
Attempt to replace the encryption key with the kernel secret (see #178)
=> [RTM] Replace the encryption key with the kernel secret

src/DataCollector/ContaoDataCollector.php, src/Resources/views/Collector/contao.html.twig
This is to be merged when the doctrine feature is available (see https://github.com/contao/core-bundle/pull/31)
=> [RTM] Removed Contao database debug info from web profiler

DEPRECATED.md, src/EventListener/InitializeSystemListener.php, src/EventListener/RefererIdListener.php, src/RefererId/TokenGenerator.php, src/Resources/config/services.yml, tests/EventListener/RefererIdListenerTest.php, tests/RefererId/TokenGeneratorTest.php, tests/TestCase.php
This PR aims to replace the `TL_REFERER_ID`. First, I wanted to implement a service but then I realized that our referer ID is in fact nothing else than an attribute of the current request because it changes for every request :-)
=> [RTM] Introduced a token generator for the referer id

src/DataCollector/ContaoDataCollector.php, src/Resources/views/Collector/contao.html.twig
=> [RTM] Fix missing table in install tool

src/Resources/contao/library/Contao/TemplateInheritance.php
=> [RTM] Add the TemplateInheritance::getTemplatePath() method (see #218).

src/Resources/config/services.yml, src/Security/Authentication/ContaoToken.php, src/Security/ContaoAuthenticator.php, src/Security/User/ContaoUserProvider.php, tests/Security/ContaoAuthenticatorTest.php, tests/Security/User/ContaoUserProviderTest.php
fixes https://github.com/contao/standard-edition/issues/7
=> [RTM] The Contao users must only be loaded if the correct scope is active

src/Resources/contao/library/Contao/Image.php, tests/Contao/ImageTest.php
Changes and tests for contao/core#7804
=> Validate coordinates in Image::setImportantPart()

src/EventListener/InitializeSystemListener.php, src/EventListener/InsecureInstallationListener.php, src/Resources/config/listener.yml, tests/EventListener/InitializeSystemListenerTest.php, tests/EventListener/InsecureInstallationListenerTest.php
See: #239 
NOTE: This PR should be rebased if #234 is merged first.
=> [RFC] Split Validate-Installation-Check

CHANGELOG.md, src/EventListener/LocaleListener.php, tests/EventListener/LocaleListenerTest.php
=> [RTM] Correctly handle an empty `_locale` attribute

src/Resources/contao/pages/PageRegular.php
=> Remove mootools for debug bar

src/Resources/contao/library/Contao/Database.php
See https://github.com/doctrine/DoctrineBundle/blob/master/Resources/doc/configuration.rst#doctrine-dbal-configuration (the second last part).
=> Use doctrine bundle's default connection

src/Resources/contao/controllers/FrontendIndex.php, src/Resources/contao/pages/PageForward.php
=> [RTM] Backwards compatibility for old page types

CHANGELOG.md, src/Resources/contao/library/Contao/StringUtil.php, src/Resources/contao/library/Contao/Validator.php, tests/Contao/ValidatorTest.php
This is the follow-up PR for #321.
@contao/developers Please review.
=> [RFC] Support unicode characters in the local part of an e-mail address

CHANGELOG.md, src/Resources/contao/classes/Backend.php, src/Resources/contao/config/mimetypes.php, src/Resources/contao/drivers/DC_Folder.php, src/Resources/contao/drivers/DC_Table.php, src/Resources/contao/library/Contao/Controller.php, src/Resources/contao/widgets/FileSelector.php, src/Resources/contao/widgets/PageSelector.php
See https://github.com/contao/core-bundle/pull/384 and https://github.com/contao/core/issues/7196.
=> [WIP] Fix the file and page search

src/Command/InstallCommand.php, tests/Command/InstallCommandTest.php
=> [RTM] Use config param upload_path upon installation 

src/Cache/ContaoCacheClearer.php, src/Cache/ContaoCacheWarmer.php, src/Command/AutomatorCommand.php, src/Command/FilesyncCommand.php, src/DataCollector/ContaoDataCollector.php, src/EventListener/AddToSearchIndexListener.php, src/EventListener/OutputFromCacheListener.php, src/EventListener/PrettyErrorScreenListener.php, src/EventListener/ToggleViewListener.php, src/EventListener/UserSessionListener.php, src/Framework/Adapter.php, src/Framework/ContaoFramework.php, src/Resources/contao/classes/BackendTemplate.php, src/Resources/contao/classes/FrontendTemplate.php, src/Resources/contao/library/Contao/Input.php, src/Resources/contao/library/Contao/Template.php, src/Resources/contao/pages/PageError403.php, src/Resources/contao/pages/PageError404.php, src/Resources/contao/pages/PageRegular.php, src/Security/Authentication/ContaoToken.php, src/Security/ContaoAuthenticator.php, src/Security/User/ContaoUserProvider.php
This is the PR for #390. It generally removes the tag and adds comments where it is kept.
=> Remove the @internal tag

src/Resources/contao/drivers/DC_Folder.php, src/Resources/contao/drivers/DC_Table.php
The only parameter in ```Message::generate()``` is now scope.
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Message.php#L129
=> Fixed the flash messages not being rendered in DC drivers

composer.json, src/Resources/config/services.yml, src/Resources/contao/classes/Messages.php, src/Resources/contao/library/Contao/Automator.php
This PR is an enhancement to #442.
=> [RTM] Use the Doctrine cache to store the latest version

src/Resources/contao/templates/block/block_searchable.html5, src/Resources/contao/templates/block/block_unsearchable.html5
it's more flexible and you can manipulate the headline block very simple
=> [RTM] Make headline a separate block element

src/Resources/contao/library/Contao/InsertTags.php
This PR implements contao/core#8172. It also allows us to remove the "nested insert tags" routines.
=> [RTM] Recursively replace insert tags

src/Resources/contao/config/config.php, src/Resources/contao/dca/tl_page.php, src/Resources/contao/languages/en/default.xlf, src/Resources/contao/languages/en/tl_page.xlf, src/Resources/contao/library/Contao/Controller.php, src/Resources/contao/models/PageModel.php, src/Resources/contao/modules/ModuleLogout.php, src/Resources/contao/pages/PageLogout.php
This PR implements #236. @contao/developers Please review.
(The missing page icon will be added automatically when we merge the back end icons branch.)
=> [RFC] Add a logout page as an alternative to the logout module

src/Resources/contao/classes/Backend.php, src/Resources/contao/dca/tl_layout.php, src/Resources/contao/languages/en/tl_layout.xlf, src/Resources/contao/library/Contao/InsertTags.php, src/Resources/contao/library/Contao/StringUtil.php, src/Resources/contao/library/Contao/System.php, src/Resources/contao/library/Contao/User.php, src/Resources/contao/models/LayoutModel.php, src/Resources/contao/models/ModuleModel.php, src/Resources/contao/models/UserGroupModel.php, src/Resources/contao/models/UserModel.php, src/Resources/contao/modules/Module.php, src/Resources/contao/pages/PageRegular.php
There are various places where the current core bundle that is still related to other bundles that must not necessarily be installed.
**Corresponding PRs:**
NewsBundle: https://github.com/contao/news-bundle/pull/4
CalendarBundle: https://github.com/contao/calendar-bundle/pull/3
FaqBundle: https://github.com/contao/faq-bundle/pull/2
If we can quickly agree on the general approach (listener with DI for hook callback etc.) I will continue migration other stuff like insert tags.
=> [RTM] Extract bundle code

CHANGELOG.md, src/Resources/config/services.yml, src/Routing/UrlGenerator.php, tests/Routing/UrlGeneratorTest.php
=> Handle the `useAutoItem` option in the URL generator

composer.json
https://github.com/contao/image/releases/tag/0.3.0
=> Update contao/image to version 0.3

src/DataCollector/ContaoDataCollector.php, src/Resources/contao/library/Contao/InsertTags.php, src/Resources/views/Collector/contao.html.twig, tests/DataCollector/ContaoDataCollectorTest.php
This PR implements contao/core#8451. @contao/developers Please review.
=> [RFC] Log unknown insert tags

src/Image/PictureFactory.php, src/Resources/contao/dca/tl_image_size.php, src/Resources/contao/languages/en/tl_image_size.xlf, src/Resources/contao/templates/picture/picture_default.html5, tests/Image/PictureFactoryTest.php
This pull request depends on #342 and adds a css class field to the image size settings.
=> [RTM] Add CSS class to image sizes

src/Command/ResetPasswordCommand.php, src/Command/UserPasswordCommand.php, tests/Command/UserPasswordCommandTest.php
This allows to reset a backend user password from the command line.
**Todo:**
=> [RTM] Password reset command

src/EventListener/StoreRefererListener.php, src/EventListener/UserAwareTrait.php, src/EventListener/UserSessionListener.php, src/Resources/config/listener.yml, tests/EventListener/StoreRefererListenerTest.php, tests/EventListener/UserSessionListenerTest.php
This PR will deprecate the `UserAwareTrait` trait and adjust the two event listeners using it.
=> [RFC] Deprecate the user aware trait

src/EventListener/StoreRefererListener.php, src/EventListener/UserSessionListener.php, tests/EventListener/StoreRefererListenerTest.php, tests/EventListener/UserSessionListenerTest.php
=> [RTM] Use AuthenticationTrustResolver to check for anonymous users

composer.json, src/Doctrine/Schema/DcaSchemaProvider.php, tests/Doctrine/Schema/DcaSchemaProviderTest.php
see http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/changelog/migration_2_5.html#mapping-allow-configuring-index-flags
=> [RTM] Fixed support for MySQL FULLTEXT index

src/DependencyInjection/Configuration.php, tests/Image/ImageFactoryTest.php, tests/TestCase.php
Use the new `interlace` option from contao/image#24
=> [RTM] Fix the JPEG interlacing

src/Resources/contao/classes/Ajax.php, src/Resources/contao/drivers/DC_Folder.php
see https://github.com/contao/core-bundle/issues/637
=> Correctly handle ajax uploads in DC_Folder

src/ContaoManager/Plugin.php
see https://github.com/contao/manager-bundle/commit/d5f890727988fb9a4d4886e9283d7cebaff2d4da
=> Core bundle must load its config files

composer.json, phpunit.xml.dist, src/Command/InstallCommand.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/ContaoCoreExtension.php, src/Resources/config/services.yml, src/Resources/contao/config/config.php, src/Resources/contao/drivers/DC_Folder.php, src/Resources/contao/library/Contao/Automator.php, src/Resources/contao/library/Contao/Image.php, tests/Command/InstallCommandTest.php, tests/Contao/ImageTest.php, tests/DependencyInjection/ContaoCoreExtensionTest.php, tests/TestCase.php
=> [RTM] contao.image.target_dir

src/Resources/contao/templates/backend/be_login.html5
As discussed in the security mailing list, see contao/core#8703
=> [RTM] Remove version number from backend login

CHANGELOG.md, DEPRECATED.md, composer.json, src/Command/InstallCommand.php, src/Command/SymlinksCommand.php, src/ContaoCoreBundle.php, src/DependencyInjection/Compiler/AddResourcesPathsPass.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/ContaoCoreExtension.php, src/Resources/config/commands.yml, src/Resources/config/services.yml, src/Resources/contao/library/Contao/Image.php, src/Resources/contao/library/Contao/System.php, src/Util/SymlinkUtil.php, tests/Command/InstallCommandTest.php, tests/Command/SymlinksCommandTest.php, tests/Command/UserPasswordCommandTest.php, tests/Config/Loader/PhpFileLoaderTest.php, tests/DependencyInjection/Compiler/AddResourcesPathsPassTest.php, tests/DependencyInjection/Compiler/DoctrineMigrationsPassTest.php, tests/DependencyInjection/ConfigurationTest.php, tests/DependencyInjection/ContaoCoreExtensionTest.php, tests/EventListener/MergeHttpHeadersListenerTest.php, tests/TestCase.php
This PR implements #758 and fixes #760.
=> Symfony 3.3 with kernel.project_dir

src/Command/AutomatorCommand.php, src/Command/FilesyncCommand.php, src/DataCollector/ContaoDataCollector.php, src/Framework/FrameworkAwareInterface.php, src/Image/LegacyResizer.php, src/Resources/config/commands.yml
This PR implements #799 for the commands. (There are a few unrelated changes which are necessary to make the bundle work with Symfony 3.3.)
=> [RTM] Auto configure the commands

src/Resources/contao/library/Contao/Template.php
I guess this goes without any further comment 😄
=> [RFC] Removed proxy cache killing varying on User-Agent

src/DataContainer/DcaFilterInterface.php, src/Resources/contao/classes/DataContainer.php, src/Resources/contao/dca/tl_user_group.php, src/Resources/contao/drivers/DC_Folder.php, src/Resources/contao/drivers/DC_Table.php, src/Resources/contao/languages/en/default.xlf, src/Resources/contao/widgets/FileTree.php, src/Resources/contao/widgets/PageTree.php
This PR implements the missing features mentioned in #816.
**TODO**
=> [RTM] Re-add the file tree widget options

UPGRADE.md
See #903 and https://github.com/contao/core/issues/4837
=> add article CSS ID change

src/Resources/contao/classes/DataContainer.php, src/Resources/contao/config/ide_compat.php
This PR is a possible fix for #886.
=> Picker without a DC object

src/Resources/contao/templates/forms/form_wrapper.html5
This adds a missing space between the form attributes.
=> Fix a "No space between attributes" error

src/Picker/FilePickerProvider.php, src/Picker/PagePickerProvider.php, src/Resources/contao/widgets/FileSelector.php
see https://github.com/contao/core/pull/8752
=> Use radio button as default for file and page picker

src/Resources/contao/dca/tl_content.php
See https://github.com/contao/calendar-bundle/pull/11#issuecomment-321615789
=> remove defaults for dcaPicker

src/Command/InstallCommand.php
see https://github.com/isotope/core/issues/1763
=> Added symlink for TCPDF config file (backwards compatibility)

src/Resources/contao/classes/DataContainer.php
=> Fix wizard css class

src/Resources/contao/library/Contao/Controller.php
=> [RFC] Created a new method braceGlob to polyfill GLOB_BRACE

src/Doctrine/Schema/DcaSchemaProvider.php, tests/Doctrine/Schema/DcaSchemaProviderTest.php
=> Fixed lowercase conversion of SQL default values

.github/CONTRIBUTING.md, CONTRIBUTING.md
Adding info on how to contribute to contao. Somehow this file is missing in the repo currently.
=> Creating CONTRIBUTING.md

src/Resources/contao/library/Contao/InsertTags.php
Works like this: `{{link_url::123|absolute}}`.
=> [RTM] Added the insert tag flag for absolute URLs

src/EventListener/BackendLocaleListener.php, src/EventListener/LocaleListener.php, src/Resources/config/listener.yml, src/Resources/config/services.yml, src/Security/Authentication/AuthenticationSuccessHandler.php, tests/DependencyInjection/ContaoCoreExtensionTest.php, tests/EventListener/BackendLocaleListenerTest.php, tests/EventListener/LocaleListenerTest.php, tests/Security/Authentication/AuthenticationSuccessHandlerTest.php, tests/Security/Authentication/FrontendAuthenticationSuccessHandlerTest.php
Fixed https://github.com/contao/core-bundle/issues/1264
=> Set locale from backend user after authentication

src/Resources/contao/drivers/DC_Folder.php, src/Resources/contao/drivers/DC_Table.php, src/Resources/contao/library/Contao/Database.php, src/Resources/contao/library/Contao/Database/Statement.php, src/Resources/contao/library/Contao/Model.php, src/Resources/contao/library/Contao/Model/QueryBuilder.php, src/Resources/contao/library/Contao/User.php, src/Resources/contao/widgets/FileSelector.php, src/Resources/contao/widgets/FileTree.php, src/Resources/contao/widgets/PageSelector.php, src/Resources/contao/widgets/PageTree.php
This is the follow-up PR to #1262.
=> Re-add identifier quoting

README.md
Not required in `composer.json`
=> Remove nelmio/security-bundle from README

README.md
See discussions/questions in https://github.com/contao/core-bundle/issues/1364 and https://github.com/contao/core-bundle/issues/1366.
=> [RFC] Updated installation documentation

composer.json
* https://github.com/contao/core-bundle/issues/1352
* https://github.com/ausi/slug-generator/issues/9
* https://github.com/contao/check/issues/136
=> require ausi/slug-generator ^1.0.1

src/EventListener/CsrfTokenCookieListener.php, tests/EventListener/CsrfTokenCookieListenerTest.php
=> [RTM] Add missing characters for token validation

tests/Contao/ControllerTest.php, tests/Contao/SystemTest.php, tests/Framework/Adapter/AdapterTest.php
Also fixes a test for outdated PHPUnit class
=> Added a few unit test for legacy classes

src/EventListener/BypassMaintenanceListener.php, src/Resources/config/listener.yml, tests/DependencyInjection/ContaoCoreExtensionTest.php, tests/EventListener/BypassMaintenanceListenerTest.php
=> Use the master request's IP to determine maintenance mode

src/DependencyInjection/Compiler/AddAssetsPackagesPass.php
This PR adds `manifest.json` support for bundle assets. If the `manifest.json` file exists in a bundle's `Resources/public` folder, it will be used for asset versioning and retrieval.
=> [RFC] Handle manifest.json in bundle public folder

gulpfile.js, package-lock.json, package.json
Makes it way easier to work with the CSS and JS files 😎
=> [RTM] Add gulp watch command

src/Resources/contao/templates/navigation/nav_default.html5
Fixes https://github.com/contao/core-bundle/issues/1504
=> Check the `accesskey` template variable

src/Resources/contao/dca/tl_user.php
Fix CS introduced in #1559. See also https://github.com/contao/core-bundle/commit/52aa6a001c813a3485610cb95ccee87f15705f72#r29337990.
=> [RFC] CS fixes

src/DependencyInjection/Compiler/RegisterHookListenersPass.php, src/Resources/contao/library/Contao/System.php, tests/DependencyInjection/Compiler/RegisterHookListenersPassTest.php
see https://github.com/contao/managed-edition/issues/38
=> Services must be public to be used in hooks

src/EventListener/SessionListener.php, tests/EventListener/SessionListenerTest.php
This disables http cache if a response has cookies.
=> [RTM] Make response with non-session cookies uncacheable
