contao/core-bundle

contao/classes/Frontend.php, contao/library/Contao/Controller.php, src/Resources/config/services.yml, src/Routing/FrontendLoader.php
I read the Symfony UrlGenerator code. If a default is set, the parameter will not be added to the query string.
=> Ignore _locale parameter if prepend_locale is off

src/EventListener/InitializeSystemListener.php
Otherwise subrequests will not be possible because of redeclared functions, `ini_set` after session-start etc.
=> The legacy code must only be initialized on master request

contao/config/default.php, contao/languages/en/exception.xlf, contao/templates/backend/be_insecure.html5, src/EventListener/InitializeSystemListener.php
This PR removes the `ignoreInsecureRoot` flag as discussed in Ahrweiler. @contao/developers Please vote.
=> Remove the ignoreInsecureRoot flag

src/Controller/BackendController.php, src/Controller/FrontendController.php, src/Routing/FrontendLoader.php, tests/Routing/FrontendLoaderTest.php
This fixes a missing container scope in the frontend and improves the loader.
We could even go as far as define the backend prefix in the `routing.yml`, which would allow people to change the route to the backend. Which would be a cool feature for Contao 4 to show off whats possible with Symfony ;-)
=> Improve routing

src/EventListener/InitializeSystemListener.php
Unfortunately, the fix in #69 was wrong, because `$route` was an absolute path including the base path.
=> [RTM] Set TL_SCRIPT to the relative base path

src/EventListener/InitializeSystemListener.php, tests/EventListener/InitializeSystemListenerTest.php
Includes commits from @dtomasi 
The framework is now also booted on a subrequest if the master request did not boot it.
=> [RFC] Prevent boot twice

src/Resources/contao/controllers/BackendIndex.php, src/Resources/contao/controllers/BackendPreview.php, src/Resources/contao/templates/backend/be_login.html5, src/Routing/FrontendLoader.php
fixes #64, so that all routes are now handled by the legacy code.
Be aware that the problem of https://github.com/contao/core/issues/7666 still exists.
=> [RTM] Adds a catch-all route

src/DependencyInjection/Configuration.php, src/DependencyInjection/ContaoCoreExtension.php, src/EventListener/InitializeSystemListener.php, src/EventListener/SessionListener.php, src/Resources/config/services.yml, src/Resources/contao/classes/Frontend.php, src/Resources/contao/classes/RebuildIndex.php, src/Resources/contao/controllers/BackendIndex.php, src/Resources/contao/controllers/BackendInstall.php, src/Resources/contao/controllers/BackendMain.php, src/Resources/contao/controllers/BackendPreview.php, src/Resources/contao/controllers/BackendSwitch.php, src/Resources/contao/library/Contao/File.php, src/Resources/contao/library/Contao/RequestToken.php, src/Resources/contao/library/Contao/Session.php, src/Resources/contao/library/Contao/User.php, src/Resources/contao/templates/analytics/analytics_google.html5, src/Resources/contao/templates/analytics/analytics_piwik.html5, src/Session/Attribute/AttributeBagAdapter.php, src/Session/Attribute/AttributeBagMirror.php, tests/EventListener/AddToSearchIndexListenerTest.php, tests/EventListener/InitializeSystemListenerTest.php, tests/EventListener/SessionListenerTest.php, tests/Session/Attribute/AttributeBagMirrorTest.php, tests/TestCase.php
Requires the following changes in `contao/standard-edition`'s `config.yml`:
```diff
-    session: false
+    csrf_protection: ~
+    session:
+        handler_id: ~
```
(I did not make a separate PR because of the effort :-)).
I know it's mixing session handling with CSRF token handling but they sort of belong together and I had to make sure I could log in again, so I hacked it all together :-)
=> [RTM] Symfony Session Handling

src/Resources/contao/config/default.php, src/Resources/contao/dca/tl_settings.php, src/Resources/contao/languages/en/tl_settings.xlf, src/Resources/contao/library/Contao/Environment.php, tests/Contao/EnvironmentTest.php
This is a PR for https://github.com/contao/core-bundle/issues/128. I checked the code and imho our legacy code does exactly what Symfony's `Request::getClientIp()` does.
Please double check this though :)
=> [RTM] Feature/trusted proxy support

src/EventListener/InitializeSystemListener.php, src/Resources/contao/library/Contao/Environment.php
We need to get rid of as much legacy code as possible in the `InitializeSystemListener`. @discordier and I are having issues with all tests failing due to (newly introducing) proper error handling and need to fix those tests which is impossible without those cleanups :)
=> [RTM] Do not use legacy code

tests/Analyzer/HtaccessAnalyzerTest.php, tests/Contao/GdImageTest.php, tests/Contao/ImageTest.php, tests/Contao/PictureTest.php, tests/DependencyInjection/ContaoCoreExtensionTest.php, tests/HttpKernel/Bundle/ContaoModuleBundleTest.php
As discussed in https://github.com/contao/core-bundle/pull/70#issuecomment-92273553 here is the separate PR for calling the setup method of the parent test case class.
=> Call parent TestCase::setUp() method in derived testcase classes.

src/EventListener/UserSessionListener.php, tests/EventListener/UserSessionListenerTest.php, tests/Fixtures/library/User.php
Follow-Up PR to https://github.com/contao/core-bundle/pull/184.
Now also contains the FrontendUser handling and does the loading process as well. In addition, `TL_REFERER_ID` has been replaced as well.
Tests still to be added.
=> [RTM] Move the user session handling to a separate listener

src/EventListener/InitializeSystemListener.php, src/EventListener/LocaleListener.php, src/Resources/config/listener.yml, src/Resources/contao/classes/BackendUser.php, src/Resources/contao/classes/FrontendUser.php, src/Resources/contao/pages/PageRegular.php, tests/EventListener/LocaleListenerTest.php
Because there will be no quick solution to #233, this pull request implements the most simple solution:
1. Use `kernel.request` event to convert our route locale (e.g. `de-CH`) to a locale ID (`de_CH`).
2. Set request and translator locale when page or user is loaded
3. Use new locale in `InitializeSystemListener`
=> [RTM] Locale handling

UPGRADE.md, src/Resources/contao/classes/Hybrid.php, src/Resources/contao/dca/tl_article.php, src/Resources/contao/dca/tl_content.php, src/Resources/contao/dca/tl_module.php, src/Resources/contao/elements/ContentAlias.php, src/Resources/contao/elements/ContentElement.php, src/Resources/contao/elements/ContentModule.php, src/Resources/contao/languages/en/tl_article.xlf, src/Resources/contao/languages/en/tl_content.xlf, src/Resources/contao/languages/en/tl_module.xlf, src/Resources/contao/library/Contao/Controller.php, src/Resources/contao/modules/Module.php
This is a PR for https://github.com/contao/core/issues/6011 (and probably a dozen more). It merges the CSS classes if an element is included in another element and also removes the "space before/after" field.
=> [RFC] Merge the CSS classes and remove the "space" setting

composer.json
This should be added to both `release/4.0.0` as well as `develop` branch as well as all the other bundles.
=> Mark release branch as 4.0.x

.gitignore, src/ContaoFramework.php, src/EventListener/PrettyErrorScreenListener.php, src/Resources/config/listener.yml, src/Resources/contao/config/config.php, src/Resources/contao/helper/functions.php, src/Resources/contao/languages/en/exception.xlf, src/Resources/contao/library/Contao/Automator.php, tests/EventListener/PrettyErrorScreenListenerTest.php
This PR includes three fixes:
* Use Monolog to log PHP errors.
* Add log entries in the pretty error screen listener.
* Use `app/logs` instead of `system/logs`.
The PR also fixes #335.
=> [RTM] Use Monolog to log PHP errors and exceptions

composer.json, src/Composer/ScriptHandler.php, tests/Composer/ScriptHandlerTest.php, tests/Fixtures/app/config/.gitignore
This adds the necessary script handler to generate the random secret for https://github.com/contao/core-bundle/issues/302
The random secret must only be generated if the `parameters.yml` file does not exist. This is because the `IncentiveeParametersHandler` will update/overwrite existing parameters if a respective environment variable is available.
Using this method means the user is not asked for a random secret on installation, but it can obviously still be changed in the `parameters.yml`.
=> [RTM] Added ScriptHandler method to generate random secret

src/EventListener/MergeHttpHeadersListener.php, src/Resources/config/listener.yml, tests/EventListener/MergeHttpHeadersListenerTest.php
This is a follow up to https://github.com/contao/core-bundle/pull/331. We still have a lot of "legacy" code that cannot properly send HTTP headers. The way to go currently is still using `header()`. However, those ones are not respected in a lot of Symfony Bundles that listen on `kernel.response` and read the `Response` object for headers and do more stuff accordingly. This PR provides a listener that merges the sent HTTP headers into the SF response object unless they were already present (so it's not possible to overwrite the ones in the response).
RFC:
=> [RTM] Added a fully unit tested MergeHttpHeadersListener

src/Resources/contao/classes/Maintenance.php, src/Resources/contao/classes/Messages.php
The app config can be adjusted to use another driver, so we should not check for the file directly.
=> Correctly use the driver to check for enabled lock

CHANGELOG.md, src/EventListener/CommandSchedulerListener.php, src/Resources/config/listener.yml, src/Resources/contao/controllers/BackendIndex.php, src/Resources/contao/controllers/FrontendCron.php, src/Resources/contao/library/Contao/Controller.php, src/Resources/contao/pages/PageRegular.php, src/Resources/contao/templates/backend/be_login.html5, tests/EventListener/CommandSchedulerListenerTest.php
This is the follow-up ticket for #244. It includes the necessary changes to trigger the command scheduler upon the `kernel.terminate` event instead of using an Ajax request.
@contao/developers Please review.
=> [RFC] Use the kernel.terminate event for the command scheduler

src/Resources/contao/library/Contao/System.php
The solution is so simple, I can't believe we did not come up with it earlier:
`System::import()` and `System::importStatic()` simply allow to pass a service name as class name.
**Example for hooks:**
```php
// config.php
$GLOBALS['TL_HOOKS']['replaceInsertTags'][] = ['app.event_listener.foo', 'replaceInsertTags'];
// foo service
public function replaceInsertTags(/** ... */) {
// just a regular function with the original arguments
}
```
This solves all issues with passing by reference etc. It also automatically enables event listener for callbacks in `DC_Table` as well as any third-party extensions that use the *correct* way of calling a hook.
**Other effects / advantages:**
In unit tests, I can now set a service called `Database` into the mock container. Which means that mocked services …
=> [RTM] Solution for event listeners

src/Cache/ContaoCacheWarmer.php
I had trouble to install Contao because composer is running the scripts and `cache:clear` by default. If the database does not yet contain Contao, it will result in an exception that `tl_page` is not found.
Not sure if this should even go into 4.0…
=> Make sure Contao is installed before warming cache

src/Framework/ContaoFramework.php, src/Resources/config/services.yml, src/Resources/contao/library/Contao/RequestToken.php, tests/Fixtures/library/RequestToken.php, tests/Framework/ContaoFrameworkTest.php, tests/TestCase.php
As discussed on Mumble, we should use the `RequestToken` class to validate the Contao request token to restore support for `disableRefererCheck`, `BYPASS_TOKEN_CHECK` and `requestTokenWhitelist`. This PR includes the necessary changes.
@contao/developers Please review.
=> [RTM] Use the RequestToken class to validate the Contao request token

src/Command/InstallCommand.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/ContaoCoreExtension.php, src/Resources/contao/config/config.php, src/Resources/contao/drivers/DC_Folder.php, src/Resources/contao/library/Contao/Automator.php, src/Resources/contao/library/Contao/Image.php, tests/Command/InstallCommandTest.php, tests/DependencyInjection/ConfigurationTest.php, tests/DependencyInjection/ContaoCoreExtensionTest.php, tests/TestCase.php
This allows to define a custom image caching path in the application configuration.
Additionally, I can define per environment if I want images to be cached. My problem is that currently the dev environment does not cache images at all. I have > 50 images on one page, which makes using the dev controller almost unbearable.
=> [RTM] Allow to configure the image dir and if to cache images

src/Resources/contao/library/Contao/System.php
I've got the following error message:
> Attempted to call an undefined method named "getData" of class "Symfony\Component\HttpFoundation\Session\Session".
This is because `System::import('Session')` would load the Symfony service instead of the legacy class.
=> Never load valid classes from service container

src/Resources/contao/library/Contao/Session.php
I first noticed that `CURRENT_ID` is no longer working in the current session.
While attempting to add that, I also noticed that my previous PR to fix `popupReferer` didn't actually handle all cases…
=> Fix CURRENT_ID and correctly map keys in all cases

src/DataCollector/ContaoDataCollector.php, src/Resources/views/Collector/contao.html.twig, src/Resources/views/Collector/contao.svg
rewrote the profiler for Symfony 2.8. Not sure if it still works/looks good with 2.7, but we should update the dependencies anyway.
=> Webprofiler redesign

src/DataContainer/PaletteManipulator.php, tests/DataContainer/PaletteManipulatorTest.php
`PaletteManipulator` is finally a helper tool to add fields in existing DCA palettes. It handles the following cases:
- Add field after existing field
- Add field before existing field
- Append field to legend
- Prepend field to legend
- Add new legend and fields after existing legend
- Add new legend and fields before existing legend
It is intentionally kept as simple as possible. I did not want to introduce object-oriented palettes, as I doubt that would be backwards compatible. The class is simply a helper to *string replace*.
I'm actually in need of such a tool to continue working on https://github.com/contao/core-bundle/pull/471. There's a field `tl_layout.calendarfeeds` and `tl_layout.newsfeeds` which should not be in `core-bundle` (see …
=> [RTM] Added PaletteManipulator

src/Resources/config/services.yml, src/Resources/contao/library/Contao/Controller.php, src/Routing/UrlGenerator.php, tests/Routing/UrlGeneratorTest.php
Per our discussion, the `UrlGenerator` is supposed to replace `Controller::generateFrontendUrl`.
It allows for simple but flexible use of Contao urls (or pages actually).
1. `$urlGenerator->generate('foo');`
> Result: `/foo.html`
2. `$urlGenerator->generate('index');`
> Result: `/`
3. `$urlGenerator->generate('foo/{items}', ['items' => 'bar']);`
> Result: `/foo/items/bar.html` if `items` **is not** in `$GLOBALS['TL_AUTO_ITEM']`
> Result: `/foo/bar.html` if `items` **is** in `$GLOBALS['TL_AUTO_ITEM']`
4. `$urlGenerator->generate('foo/{items}', ['items' => 'bar', 'auto_item' => 'items']);`
> Result: `/foo/bar.html` (regardless of `$GLOBALS['TL_AUTO_ITEM']`)
5. `$urlGenerator->generate('foo/{items}/{article}', ['items' => 'bar', 'article' => 'test');`
> Result: `/foo/bar/article/test.html` …
=> [RFC] Url generator

src/Resources/contao/classes/Backend.php, src/Resources/contao/library/Contao/Controller.php, src/Resources/contao/models/PageModel.php
This is the follow-up PR to #480. As discussed, I have deprecated the `getFrontendUrl()` method and copied some logic to the `PageModel::getFrontendUrl()` class.
@contao/developers Please review.
=> [RFC] Deprecate the generateFrontendUrl() method

src/Resources/contao/classes/Frontend.php, src/Resources/contao/pages/PageError404.php
This is the follow-up PR to contao/core#8331.
@fritzmg Does it solve your issue?
@Toflar Is `varchar(255)` long enough to store the full URI?
=> [RFC] Store the full URI in the search results

src/Resources/contao/controllers/FrontendIndex.php, src/Resources/contao/modules/ModuleSearch.php
This PR will change the log level of the "No active page for page ID" message from "error" to "general", which stops the app from logging them in the `app/logs/prod-*.log` file.
This is a security enhancement, which shall prevent storage overflow attacks.
@contao/developers Any objections?
=> [RFC] Do not spam the system log

CHANGELOG.md, src/Resources/contao/dca/tl_layout.php, src/Resources/contao/languages/en/tl_layout.xlf, src/Resources/contao/library/Contao/Combiner.php, src/Resources/contao/library/Contao/Controller.php, src/Resources/contao/models/LayoutModel.php, src/Resources/contao/models/PageModel.php, src/Resources/contao/pages/PageRegular.php, src/Resources/contao/templates/backend/be_alerts.html5, src/Resources/contao/templates/backend/be_confirm.html5, src/Resources/contao/templates/backend/be_diff.html5, src/Resources/contao/templates/backend/be_help.html5, src/Resources/contao/templates/backend/be_login.html5, src/Resources/contao/templates/backend/be_main.html5, src/Resources/contao/templates/backend/be_password.html5, src/Resources/contao/templates/backend/be_picker.html5, src/Resources/contao/templates/backend/be_popup.html5, src/Resources/contao/templates/backend/be_switch.html5, src/Resources/contao/templates/mootools/moo_chosen.html5
Make script combination optional in case the website supports HTTP/2 (see #484). There is a [related PR for the installation bundle](https://github.com/contao/installation-bundle/pull/23), which also needs to be merged when merging this PR.
@contao/developers /cc
=> [RFC] Make script combination optional

src/Resources/contao/library/Contao/Model.php
this will make developer live soooo much easier by simply opting-in on arrays 😎 
Also solves https://github.com/contao/core/issues/6147
=> [RTM] Allow Model::find() to return arrays instead of collections

src/Image/ImageFactory.php, src/Image/ImageFactoryInterface.php, src/Image/PictureFactory.php, src/Image/PictureFactoryInterface.php, src/Resources/contao/dca/tl_theme.php, src/Resources/contao/languages/en/tl_theme.xlf, src/Resources/contao/pages/PageRegular.php, tests/Image/ImageFactoryTest.php, tests/Image/PictureFactoryTest.php
This pull request depends on #342 and adds a default image densities field to the theme settings.
See contao/core#8171
=> [RTM] Add default image densities to theme settings

src/Image/ImageFactory.php, src/Image/ImageFactoryInterface.php, src/Image/PictureFactory.php, src/Image/PictureFactoryInterface.php
The constructors should be removed from the interfaces as we did in contao/image#10.
=> [RTM] Remove constructors from image and picture factory interfaces

src/Resources/contao/library/Contao/File.php
On an article overview page with 50 pages/articles this change brings the response time from about 1800ms down to about 700ms.
This change should be OK to merge into 4.3 I think.
This is the alternative of #626
It may be useful to merge this back into 3.5...
=> [RFC] Fix performance of File::$imageSize

src/Resources/contao/library/Contao/Config.php
Since the localconfig parameters can be specified in the container, we don't need the file to be present.
=> Allow to run Contao without a localconfig.php

src/Image/ImageFactory.php, tests/Image/ImageFactoryTest.php
There is a bug if the important part from the database does not fit inside the image dimensions.
Steps to reproduce:
1. Add an important part to a large image
2. Replace the image with a much smaller one
3. Open the contao filemanager
This results in the `OutOfBoundsException`: *“Crop coordinates must start at minimum 0, 0 position from top left corner, crop height and width must be positive integers and must not exceed the current image borders”*
=> Ignore the important part if it does not fit

src/Config/Loader/XliffFileLoader.php, tests/Config/Loader/XliffFileLoaderTest.php, tests/Fixtures/vendor/contao/test-bundle/Resources/contao/languages/en/default.xlf
Fixes #642
The loader should behave the same way as before, but instead of the hardcoded assumption that the source language is `en` it respects the value of the XLIFF attribute `source-language`.
=> [RTM] Respect the XLIFF source-language attribute

src/Cache/ContaoCacheWarmer.php
Since we added template autoloading in Contao 4.3 the `autoload.php` is not used anymore. If no bundle contains it, the cache warmup will fail.
=> [RFC] Cache build fails without autoload.php

src/Command/VersionCommand.php
This PR will deprecate the contao:version command (see #665).
=> [RTM] Deprecate the contao:version command

src/Resources/contao/library/Contao/Controller.php, src/Resources/contao/library/Contao/InsertTags.php, src/Resources/contao/library/Contao/Picture.php, tests/Contao/PictureTest.php
Fixes #659
The legacy Picture class in Contao 4.2 used the `TL_FILES_URL` constant in [Picture.php:281](https://github.com/contao/core-bundle/blob/58cf7360ddebbcffb51020d7ddd2892d71bd5c79/src/Resources/contao/library/Contao/Picture.php#L281). This is missing now and so the `TL_FILES_URL` is currently ignored in pictures. To fix it I added the constant to all `Picture::getImg()` and `Picture::getSources()` calls.
=> [RFC] Fix missing TL_FILES_URL for pictures

.ide-toolbox.metadata.json
The [PHP Toolbox](https://plugins.jetbrains.com/plugin/8133) plugin adds customizable autocomplete additions to PhpStorm. Here's a simple draft for Contao `core-bundle`.
- Autocomplete and type detection of `ContaoFrameworkInterface::getAdapter()`
- Autocomplete for DCA and languages (currently hardcoded)
- Autocomplete for model options
These are just examples and if we come up with more ideas it's highly extendable 😎
=> [RTM] PHP Toolbox support

src/Resources/contao/library/Contao/Combiner.php, tests/Contao/CombinerTest.php, tests/TestCase.php
=> [RTM] Use the contao.web_dir parameter in the Combiner

src/Resources/config/services.yml, src/Twig/Extension/ContaoTemplateExtension.php, tests/Twig/Extension/ContaoTemplateExtensionTest.php
Two things changed:
* We now use the `RequestMatcher` instead of directly check the request attribute in the request object
* Renamed `contaoFramework` to `framework`
=> [RFC] Use scope matcher instead of directly check for the request attribute

.travis.yml, appveyor.yml, src/Resources/config/services.yml, src/Resources/contao/library/Contao/ClassLoader.php, src/Resources/contao/library/Contao/ModuleLoader.php, src/Security/ContaoAuthenticator.php, src/Security/User/ContaoUserProvider.php, tests/Security/ContaoAuthenticatorTest.php, tests/Security/User/ContaoUserProviderTest.php
=> [RFC] Fix deprecations in unit tests

src/ContaoCoreBundle.php, src/DependencyInjection/Compiler/DoctrineTypesPass.php, src/Doctrine/DBAL/Types/BinaryStringType.php, tests/Doctrine/DBAL/Types/BinaryStringTypeTest.php
Our current UUID field types are not supported by Doctrine. I started using ORM and the binary column was not usable because it returns a resource by default.
I think Contao core bundle should provide a type to handle it's default fields.
=> [RTM] Added a DBAL field type for UUIDs

src/Resources/contao/controllers/FrontendIndex.php
Passing a `PageModel` object is valid for the method, but the `count()` method does not exist.
=> [RTM] Fixed call to count() method on page objects

src/ContaoManager/Plugin.php
as discussed in https://github.com/contao/manager-bundle/issues/13, the core bundle should know it's dependencies.
=> Add bundle requirements to manager plugin

src/EventListener/MergeHttpHeadersListener.php
When you get PHP warnings because you did something wrong and their not suppressed, headers will be already sent by the time our listener is triggered.
It will cause yet another warning because headers are already sent.
Not a big deal but we should not try to work on the headers if they're already sent because it possibly won't do anything at all anyway as the header might be already sent :-)
=> Only remove headers if not already sent

CHANGELOG.md, src/Resources/contao/library/Contao/System.php
This simple change should get us closer to actually callables.
You can now use `[$this, 'foobar']` for a callback. 
**Example for current:**
```php
$GLOBALS['TL_DCA']['tl_example']['config']['onload_callback'][] = function () {
$this->onLoad();
};
```
**Example for new:**
```php
$GLOBALS['TL_DCA']['tl_example']['config']['onload_callback'][] = [$this, 'onLoad'];
```
=> [RTM] Allow to pass objects in callback arrays

src/Resources/contao/controllers/FrontendIndex.php, src/Resources/contao/library/Contao/File.php, src/Resources/contao/library/Contao/InsertTags.php, src/Resources/contao/library/Contao/TemplateInheritance.php, tests/Contao/TemplateTest.php
As discussed in https://github.com/contao/core-bundle/pull/698#issuecomment-279708701
@antoinedavid can you verify that this solves your issue with `sendToBrowser()`?
=> [RFC] Use try-finally blocks to close all opened output buffers

src/Resources/contao/library/Contao/Widget.php
Since Contao 4.3 we can set an array for the SQL definition in DCAs. However, the default value and other configs were not correctly detected/merged.
=> [RFC] Correctly parse Doctrine SQL array

src/Resources/contao/library/Contao/Widget.php, tests/Contao/WidgetTest.php
I suppose it will probably still take some time until our widgets become obsolete so here's something we should have had ever since there was Contao :-P
=> [RTM] Allow to manually pass a value to any widget

src/Resources/contao/library/Contao/Image.php
Using the legacy image class `\Image::get('image.jpg', 100, 100);` generates URLs like `app/../assets/images/5/image-42ccae20.jpg`. This was fixed for the new image services in contao/image#16 but we missed the legacy image class. This pull request fixes that.
=> [RTM] Fix bug with relative ../ parts in image URLs

src/Resources/contao/library/Contao/DcaExtractor.php
The install tool currently shows the deprecation message *“Using database.sql files has been deprecated and will no longer work in Contao 5.0. Use a DCA file instead.”* because it thinks `tl_templates` uses a *database.sql* file.
With this PR `DC_Folder`s that are not database assisted get skipped in the `DcaExtractor`.
=> [RTM] Skip folder DCs that are not database assisted in DcaExtractor

src/Resources/contao/library/Contao/Template.php
Fix for https://github.com/contao/core/issues/8686.
Was actually way easier than I thought because we don't need the debug bundle for dumping the template vars. Here's the output:
Oh, and here's what you will be able to do when Symfony 3.3 is released and you hit <kbd>CTRL</kbd>/<kbd>CMD</kbd> + <kbd>F</kbd>:
Symfony ❤️
=> Use the SF var dumper directly to show template variables

src/Resources/contao/classes/FrontendTemplate.php, src/Resources/contao/models/PageModel.php
If you set a cache time in the root page of a website and want to overwrite it with `0` in a subpage it doesn’t work currently because the check doesn’t differentiate between `0` and `false`.
=> [RTM] Fix bug overwriting cache/clientCache with zero values

src/Resources/contao/classes/DataContainer.php, src/Resources/contao/controllers/BackendPassword.php, src/Resources/contao/forms/FormPassword.php, src/Resources/contao/library/Contao/User.php, src/Resources/contao/library/Contao/Widget.php, src/Resources/contao/widgets/Password.php
Here's another feature for Contao 4.4.
For my own modules I want to be able to disable the input encoding all together and output stuff using twig or encode it myself. I have an application which even doesn't output anything at all but manages content that's fetched through an API. I have to set the `eval` attributes on every field which is a bit tedious. I think it can be very helpful to disable this completely and prepare for the future already in your own bundles/applications :-)
=> [RTM] Allow to disable input encoding for a whole dca

src/Resources/contao/library/Contao/InsertTags.php
Same issue as mentioned multiple times: When a page is cached (in case of Contao 3.5) there's no environment information anymore. That's why every fragment that wants to be included using ESI (in Contao 4) needs to make sure it works 100% without any dependencies.
I've added the `request` query parameter to pass on the original request to the ESI request string and while I was on it, also passed on the `pageId` parameter.
Again, there might be a lot of other use cases and we just cannot fix them all with the software architecture we currently have. I'm working on it and these small PR's are tiny step-by-step fixes so that at least the core works fine (if an extension dev needs another param, we might provide it until the proper solution was implemented).
=> [RTM] Fixed {{toggle_view}} insert tag

CHANGELOG.md, src/Resources/contao/classes/Backend.php, src/Resources/contao/dca/tl_content.php, src/Resources/contao/dca/tl_module.php, src/Resources/contao/elements/ContentAccordion.php, src/Resources/contao/elements/ContentHyperlink.php, src/Resources/contao/elements/ContentImage.php, src/Resources/contao/elements/ContentText.php, src/Resources/contao/languages/en/tl_content.xlf, src/Resources/contao/library/Contao/Controller.php
This PR implements contao/core#7774. It is still work in progress, but it already works for adding images to text elements.
=> [RTM] Use the file meta data by default when adding an image

src/Resources/contao/library/Contao/InsertTags.php
See https://github.com/contao/core-bundle/issues/731#issuecomment-295773166
@Toflar and I discussed this in IRC and we came to the conclusion, that this condition
```php
($elements[0] == 'file' && !\Validator::isStringUuid($elements[1]))
```
could simply be dropped from [InsertTags.php#L119](https://github.com/contao/core-bundle/blob/4.3.9/src/Resources/contao/library/Contao/InsertTags.php#L119) altogether.
This way the user/developer can decide himself, whether or not a `{{file::PATH}}` insert tag should be uncached or not.
Previous behaviour in Contao 3 was, that `{{file::UUID}}` and `{{file::PATH}}` insert tags are always forced to be uncached (see [InsertTags.php#L94](https://github.com/contao/core/blob/3.5.27/system/modules/core/library/Contao/InsertTags.php#L94)). This creates a …
=> do not force {{file::PATH}} insert tags to be uncached

src/Resources/views/Backend/be_page.html.twig
See #823.
It's obviously a typo...
=> Fix key/value pairs

src/Resources/contao/languages/en/exception.xlf
This adds the new/old route to the Contao install tool.
=> install.php not working

CHANGELOG.md, src/Resources/contao/forms/FormCaptcha.php, src/Resources/contao/templates/forms/form_captcha.html5
With these changes we would achieve the following:
1. Normal users won’t see the captcha field and can just submit the form.
2. If a user is detected as a spam bot, they can still send the form by answering the captcha question.
3. Bots that don’t support JS, or that can’t resist the honeypot cannot send the form.
=> [RFC] Hide captcha field for users and add honeypot field

src/Resources/contao/forms/FormCaptcha.php
This should improve the stability of `getQuestion()` and `getSum()`. Now they can be called in any order and multiple times. See #832
=> [RTM] Only generate captcha values once

src/Cors/WebsiteRootsConfigProvider.php
Due to your MySQL server setup (e.g. allow anonymous connection), the existing check was successful but the call to `tableExists` results in an exception.
=> Fix install tool displaying "incomplete installation" exception

src/Cors/WebsiteRootsConfigProvider.php, tests/Cors/WebsiteRootsConfigProviderTest.php
Fix for https://github.com/contao/installation-bundle/issues/56, see [explanation](https://github.com/contao/installation-bundle/issues/56#issuecomment-309824158).
This PR changes the CORS detection to the same methodology as used in [nelmio/NelmioCorsBundle/EventListener/CorsListener.php#L68](https://github.com/nelmio/NelmioCorsBundle/blob/1.5.3/EventListener/CorsListener.php#L68).
This way the Install Tool works in browsers like Chrome and Safari as well (who set the `Origin` header on `POST` requests).
=> [WIP] Fix CORS detection

src/Resources/contao/classes/DataContainer.php, src/Resources/contao/drivers/DC_Folder.php, src/Resources/contao/drivers/DC_Table.php
fixes #883
Unfortunately, there's no cleaner solution…
Also tested to edit a page within the page picker and pick another page for the redirect 💪
=> Allow recursive dca picker in the same table

src/Resources/contao/classes/BackendUser.php
Since Contao 4.4, the backend menu requires extensions to always render submenu items. I have fixed this in the core by always passing `$blnShowAll=true` to the hooks and then handle collapsing in the navigation method. This also correctly marks active items if they follow the default naming, which were previously ignored in extensions.
=> Correctly handle active menu states in the new menu markup

src/Resources/contao/dca/tl_form_field.php
Imho the default value for `tl_form_field.extensions` should also contain the new MS Office formats, similar to [config/default.php#L62-L68](https://github.com/contao/core-bundle/blob/4.4.0/src/Resources/contao/config/default.php#L62-L68)
=> Add new MS Office formats

src/Resources/contao/library/Contao/Email.php
In Contao 3 it was possible to override the mailer configuration by replacing the global constants. We did such things in Notification Center (see #128).
In Contao 4 this no longer works because the container mailer is used. It should be possible to override this. Ideally, this could be merged as a bugfix because otherwise a few extensions will have issues to fix such bugs until the next minor 😶
=> Allow to override the mailer configuration in Email class

src/EventListener/MergeHttpHeadersListener.php, tests/EventListener/MergeHttpHeadersListenerTest.php
After hours of debugging @aschempp and me finally found the issue for some redirect and cookie issues in Contao 4.4. They were introduced by using our header-replay-bundle but it was actually not the reason for the bug. The bug is that the listener instance is created once and we do not lazily fetch the headers using `headers_list()`. Now when you are using multiple request->response iterations within the same php process (which is one big advantage of Symfony and which was not noticed before because nobody did that apparently) the headers that are sent in between these iterations are ignored. We have to always fetch them lazily.
=> Fixed merge http headers listener not working with Symfony's request stack

src/Resources/contao/library/Contao/Database.php
I know the usage of `\Database::getInstance(array(…))` is deprecated - but in case anyone still uses this, they might run into the following issue:
In Contao 3 the character set of the database connection was defined via `$GLOBALS['TL_CONFIG']['dbCharset']`, (which defaults to `UTF8`, see [system/config/default.php#L140](https://github.com/contao/core/blob/3.5.28/system/config/default.php#L140); In Contao 4, the default doctrine database connection also defaults to `UTF8`, see [contao-manager/doctrine.yml#L20](https://github.com/contao/manager-bundle/blob/4.4.1/src/Resources/contao-manager/doctrine.yml#L20)).
However, the character set configuration is missing when using
```php
\Database::getInstance(array
(
'dbHost' => '…',
'dbPort' => '…',
'dbUser' => '…',
'dbPass' => '…',
'dbDatabase' …
```
=> add missing charset parameter for database config

src/EventListener/HeaderReplay/BackendSessionListener.php, tests/EventListener/HeaderReplay/BackendSessionListenerTest.php
The listener was only triggered in the back end, however it needs to be triggered in the front end (front end preview). This was the reason that the "log in as member" feature did not work.
=> Fix the back end session listener

src/Resources/contao/drivers/DC_Folder.php
Can we also clear the script cache when editing a js file with the source editor?
=> [RFC] Clear script cache when editing js files

tests/Command/InstallCommandTest.php, tests/Picker/FilePickerProviderTest.php
See #1061 
@aschempp Is my change in *FilePickerProviderTest.php* correct? I think the `PickerConfig` only handles relative paths, not absolute ones.
=> [RFC] Fix failing tests on Windows

src/Framework/ContaoFramework.php
When there is an exception (such as if a route does not exist at all) during route generation, our pretty error screen listener fails because the framework does not boot properly. Is there any reason why we only catch the - global - InvalidArgumentException here?
=> Catch general exceptions during route generation

src/Resources/config/services.yml, src/Translation/Translator.php, tests/Translation/TranslatorTest.php
Can be used as following:
```php
->trans('MSC.view', [], 'contao_default');
->trans('ERR.minlength', ['My Field', 1234], 'contao_default');
->trans('websiteTitle.0', [], 'contao_tl_settings');
->trans('MSC.key\.mit\.punkt\.und\\\\backslash', 'contao_default');
```
Twig:
```twig
{% trans_default_domain 'contao_default' %}
{{ 'MSC.view'|trans }}
{{ 'ERR.minlength'|trans(['My Field', 1234]) }}
{{ 'websiteTitle.0'|trans({}, 'contao_tl_settings') }}
{{ 'MSC.key\\.mit\\.punkt\\.und\\\\backslash'|trans }}
```
=> [RTM] Translator

src/Resources/contao/config/default.php
The old defaults for the `imageWidth` and `imageHeight` setting seem a bit low to me, especially in these modern times, with responsive images and high DPI display devices.
I recently forgot to change these values and now a customer needs to re-upload all pictures again, since they all got automatically downscaled to 800x600 -_-
Not sure what the new defaults should be though. 1280? 1680? 1920?
=> [RTM] increase imageWidth/Height default

src/Resources/contao/library/Contao/User.php
This should prevent `1054 Unknown column '...' in 'field list'` errors.
=> Validate array keys before saving to tl_user

CHANGELOG.md, src/ContaoCoreBundle.php, src/DependencyInjection/Compiler/RegisterHooksPass.php, src/Framework/ContaoFramework.php, tests/DependencyInjection/Compiler/RegisterHooksPassTest.php, tests/Framework/ContaoFrameworkTest.php, tests/TestCase.php
Since https://github.com/contao/core-bundle/pull/376 it's possible to use services for hooks. This is a great step to using services within Contao.
This PR completes this step by allowing to register hooks as services without using the `config.php`. You don't have to manage your hook registration at two places anymore.
```yaml
services:
my.custom.hook_listener:
class: 'My\Custom\Hook\Listener'
tags:
- { name: 'contao.hook', hook: 'parseTemplate', method: 'onParseTemplate'}
- { name: 'contao.hook', hook: 'initializeSystem', method: 'onInitializeSystem', before: true}
```
I'm aware of the above mentioned PR discussed it before and this feature wasn't added because of lack of control the position of the hook.
To gain more control of the position it's possible to set the `before` attribute so …
=> [RTM] Allow to register hooks listeners as tagged services

src/Resources/contao/forms/FormPassword.php, src/Resources/contao/widgets/Password.php
Check the minimum password length first from DCA 'eval' value, if it does not exists use the value from Config as fallback.
=> [RTM] Minimum password length enhancement

src/Resources/contao/classes/Versions.php
With this PR I want to add the possibility to save versions in the `tl_version` table, which are not directly editable and therefore should not be  shown on the welcome page.
This makes the version table useable for extensions to save versions for extra data.
As far as I understand, the editUrl is always saved when a new version is created. So I simply added an extra WHERE statement. Another solution would be to have an extra `hide` column.
**To give an example for a use case:**
I have an extension which saves extra data related (and edited) with content elements in an extra table. When the content element is saved, a version is created and I use the `oncreate_version_callback` to save a version for the extra data, too. But these are not directly editable and makes the 'Last changes' …
=> [RFC] Add the possibility to save hidden version data

src/DependencyInjection/Compiler/RegisterHookListenersPass.php, tests/DependencyInjection/Compiler/RegisterHookListenersPassTest.php
This will remove the need to set a method name for hook event listeners. The name is automatically generated from hook name, if it is not set in the tag.
```
// config.yml
services:
App\EventListener\MyListener:
tags:
- { name: contao.hook, hook: generatePage }
```
```php
// MyListener.php
class MyListener
{
public function onGeneratePage(…$foo)
{
}
}
```
=> [RTM] Generate the method name from hook

src/DependencyInjection/Compiler/AddAssetsPackagesPass.php, tests/DependencyInjection/Compiler/AddAssetsPackagesPassTest.php
This will slightly change the behavior, we're always using a name generated from bundle class instead of using the extension alias if available. It should not make a difference for correctly configured bundles, except for the core bundle where it's even better, because previously it was `contao` and now it's `contao_core`.
=> Fixed use of kernel service in assets packages pass

src/Resources/contao/config/config.php, src/Resources/contao/dca/tl_form_field.php, src/Resources/contao/forms/FormFieldsetStart.php, src/Resources/contao/forms/FormFieldsetStop.php, src/Resources/contao/languages/en/tl_form_field.xlf, src/Resources/contao/templates/forms/form_fieldsetStart.html5, src/Resources/contao/templates/forms/form_fieldsetStop.html5
Wrapper elements provides a cleaner view of complex elements in the parent view. As the feature is not limited to CEs it would be nice to use it for form fieldsets as well.
If this PR is accepted I'll provide the missing tasks as well.
=> [RTM] Display form fieldsets as wrappers in the backend view.

README.md
=> Removed scrutinizer-ci badge

README.md
Add default `token_lifetime` to example configuration.
=> Add token_lifetime to config

src/Resources/contao/classes/StyleSheets.php
Preservation of HTML entered in the custom code field of a style sheet format definition was implemented here:
f4d6e5434a6e9146c33cb8df39d80a3c00eeaaf1 (History in contao/core: https://github.com/contao/core/pull/6667 https://github.com/contao/core/commit/c61c697278ca51f86fca96e08791073b45c197bc)
However, the above only applies for the generated asset file. When the "Export style sheet" feature is used, all special characters in the created file will be converted to HTML entities.
To reproduce the issue, create a format definition (e. g. `.foo:before`) and add custom code (e. g. `content: "";`), then go back to the overview of style sheets and select "Export style sheet ID n". The resulting file will contain this:
```
.foo:before {
content: &quot;&quot;;
}
```
To resolve the issue, check …
=> Do not encode chars from custom code field in exported style sheet

composer.json, src/Resources/contao/templates/elements/ce_vimeo.html5, src/Resources/contao/templates/elements/ce_youtube.html5
Having `frameborder="0"` on iframes produces the following validation error:
```
The frameborder attribute on the iframe element is obsolete. Use CSS instead.
```
See https://validator.w3.org/nu/?doc=https%3A%2F%2Fdemo.contao.org%2Fen%2Fmedia-elements.html
_Note:_ there are a few places in the back end where `frameborder="0"` is used on iframes as well (`be_preview.html5`, `core.js`). Those are not changed with this PR.
=> remove frameborder attribute from media iframes

src/EventListener/MergeHttpHeadersListener.php
This is the quick fix for Contao 4.4.
I'm working on a better solution for Contao 4.5 (which is not possible to merge in 4.4 because of security and request token handling).
=> Never merge cache-control headers

src/Resources/contao/drivers/DC_Table.php, src/Resources/contao/library/Contao/Database.php, src/Resources/contao/library/Contao/Database/Statement.php, src/Resources/contao/library/Contao/Model.php, src/Resources/contao/library/Contao/Model/QueryBuilder.php, src/Resources/contao/library/Contao/User.php, src/Resources/contao/widgets/FileSelector.php, src/Resources/contao/widgets/FileTree.php, src/Resources/contao/widgets/PageSelector.php, src/Resources/contao/widgets/PageTree.php
This is the port of contao/core#8813.
Also see #1106 and contao/installation-bundle#70
=> [RTM] Quote reserved words in database queries

CHANGELOG.md, src/Doctrine/Schema/DcaSchemaProvider.php, tests/Doctrine/DoctrineTestCase.php, tests/Doctrine/Schema/DcaSchemaProviderTest.php
This PR fixes #1286 as discussed with @aschempp. It handles the following cases:
* `'sql' => "varchar(128) BINARY NOT NULL default ''"`
* `'sql' => ['type' => 'string', 'length' => 128, 'not_null' => false, 'default' => '', 'customSchemaOptions' => ['case_sensitive' => true]]`
=> Use the BINARY flag instead of COLLATE *_bin

src/Session/LazySessionAccess.php, src/Session/MockNativeSessionStorage.php, tests/Session/LazySessionAccessTest.php
This pull request fixes the issues with accessing nested variables of `$_SESSION`.
Related: #1260
=> [RFC] Enable access to nested keys in $_SESSION via LazySessionAccess

src/Menu/BackendMenuRenderer.php, tests/Menu/BackendMenuRendererTest.php
Details available in [this PR](https://github.com/contao/core-bundle/pull/1379).
> Update to the modern @-prefixed way of referencing templates.
=> Use the modern @-notation when referencing twig templates for Menu

src/Resources/config/services.yml, src/Resources/views/Collector/contao.html.twig, tests/DependencyInjection/ContaoCoreExtensionTest.php
The Contao DataCollector used an outdated method for referencing templates which
seen to have been remove recently. Update to the modern @-prefixed way of referencing
templates.
Fixes the following error (occures when opening the debugger, or even just show the debug toolbar).
```
The profiler template "ContaoCore:Collector:contao.html.twig" for data collector "contao" does not exist.
UnexpectedValueException
in vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Profiler/TemplateManager.php (line 108)
```
> In the past, Symfony used a different syntax to refer to templates. This format, which uses colons (:) to separate each template path section, is less consistent and has worse performance than the Twig syntax. (https://symfony.com/doc/3.4/templating/namespaced_paths.html)
> …
=> [RFC] Fix namespaced paths in Contao DataCollector

src/Controller/InsertTagsController.php, src/Resources/contao/library/Contao/InsertTags.php, tests/Controller/InsertTagsControllerTest.php
Otherwise the main request will never allow for client cache as it takes the lowest value of all fragments (which is 0 at the moment for us).
=> Make sure insert tags get the same client cache time as the page

src/EventListener/CsrfTokenCookieListener.php, tests/EventListener/CsrfTokenCookieListenerTest.php
CSRF tokens should only consist of charaters and numbers.
=> [RTM] Validate CSRF cookie

src/Resources/contao/dca/tl_page.php
This enables you to conveniently select news or events (or more) for external redirect pages.
=> use dcaPicker for url field

src/Command/AutomatorCommand.php, src/Resources/config/commands.yml, tests/Command/AutomatorCommandTest.php
`InputArgument` enforces its third parameter (`description`) to be of type `string`, so our nice way of assuring the lazy loading of the description (providing `$this` with a `__toString`) method does not work anymore in `symfony/console ^4.0`.
I refactored it to use a service argument.
=> Fixed argument types for AutomatorCommand in symfony/console ^4.0

src/EventListener/InsertTags/TranslationListener.php, src/Resources/config/listener.yml, tests/EventListener/InsertTags/TranslationListenerTest.php
Contao 4.5 supports the Symfony translator, but there is no insert tag to use the Symfony translator. Here's a fix for that.
- `{{trans::foo_bar}}` => Replace `foo_bar` with the default message domain (*messages*), mostly not useful
- `{{trans::foo_bar::app}}` => Replace `foo_bar` from `app` message domain
- `{{trans::foo_bar::app::param1:param2}}` => Replace `foo_bar` from `app` message domain with parameters `param1` and `param2`. The parameters are separated by single colons, like they are for the `label` insert tag.
=> [RTM] Added insert tag for translator

src/Resources/contao/templates/backend/be_login.html5
Added blocks like here:
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/backend/be_main.html5
With blocks it should be possible to add content in a child template (Template inheritance) like described in the book here: https://docs.contao.org/books/manual/4.0/en/04-managing-content/templates.html
Use case: Wanted to add a custom logo with CSS in the Login page...
=> [RTM] Add template blocks to be_login.php

src/Resources/contao/dca/tl_module.php
While working on #1462 I noticed that `tl_modules.pages` has `'files'=>true` set in its `eval`. That does not make any sense, does it?
=> remove 'files'=>true for pages

src/Resources/contao/library/Contao/StringUtil.php
This PR uses a simple regex to filter strings which are definitely not serialized strings. It noticeably reduces the number of `unserialize()` calls and speeds up the method by up to 70% (see https://3v4l.org/F3gdM and https://3v4l.org/6oSrr).
=> Optimize the StringUtil::deserialize() method

src/Resources/contao/dca/tl_module.php, src/Resources/contao/languages/en/tl_module.xlf, src/Resources/contao/modules/ModuleSearch.php
These changes allow you to expand/limit the search to multiple pages or website roots. This enables you to:
* limit the search to multiple pages and its children - instead of just one page and its children
* expand the search over multiple website roots - instead of being restricted to the current website root
The changes are fairly simple and straight forward. I tagged it as RFC since I am unsure whether the use of a new field called `searchPages` is really necessary. I decided to not use the existing `pages` field, since the sort order does not matter. Though may be I should simply alter the DCA in a `load_callback`, similar to `tl_content::setSingleSrcFlags`? Then the `pages` field could be reused for this.
=> [RTM] allow multi root and multi page search

.travis.yml, composer.json
```
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package satooshi/php-coveralls is abandoned, you should avoid using it. Use php-coveralls/php-coveralls instead.
```
Don't know if we can use `php-coveralls/php-coveralls` in version `2.x`.
=> [RFC] Fix abandoned packages on composer install/update

src/Controller/AbstractFragmentController.php, src/Controller/ContentElement/AbstractContentElementController.php, src/Controller/FrontendController/AbstractFrontendModuleController.php, src/Controller/FrontendModule/AbstractFrontendModuleController.php, src/DependencyInjection/Compiler/RegisterFragmentsPass.php, src/Fragment/ForwardFragmentRenderer.php, src/Fragment/FragmentConfig.php, src/Fragment/FragmentOptionsAwareInterface.php, src/Fragment/Reference/ContentElementReference.php, src/Fragment/Reference/FrontendModuleReference.php, src/Resources/config/services.yml, src/Resources/contao/library/Contao/Model.php, src/Resources/contao/models/ContentModel.php, tests/Controller/ContentElement/ContentElementControllerTest.php, tests/Controller/FrontendModule/FrontendModuleControllerTest.php, tests/DependencyInjection/Compiler/RegisterFragmentsPassTest.php, tests/DependencyInjection/ContaoCoreExtensionTest.php, tests/Fixtures/Controller/ContentElement/TestController.php, tests/Fixtures/Controller/FrontendModule/TestController.php
Abstract controllers that implement the same features as the abstract `ContentElement` and `Module` classes did.
=> [RTM] Draft of Contao controllers

src/EventListener/ClearFormDataListener.php, src/Resources/config/listener.yml, tests/DependencyInjection/ContaoCoreExtensionTest.php, tests/EventListener/ClearFormDataListenerTest.php
=> [RTM] Auto-clear the session form data

composer.json
Enables automatic sorting for packages in `composer.json` (see https://getcomposer.org/doc/06-config.md#sort-packages).
=> [RFC] Enable package auto sorting for composer

src/Resources/contao/modules/ModuleSearch.php
At the moment it's not possible to access enriched search result data in the `search_*` template. Such data could be added using the `indexPage` hook, f.e. a preview image or additional descriptions. 
This pull requests provides access to all data being stored in the `tl_search` dataset.
=> Pass search result data to the search template

src/Resources/contao/dca/tl_article.php
See https://github.com/contao/news-bundle/pull/37
=> reduce memory consumption during sitemap generation

src/Resources/contao/templates/frontend/fe_page.html5, src/Resources/contao/templates/modules/mod_breadcrumb.html5
This should fix #1421 and #1429.
I think the problem why Google does not show the breadcrumb in the search results is because of a missing link between the webpage and the breadcrumb. This can be fixed by adding `itemprop="breadcrumb"` to mod_breadcrumb and removing the header, main and footer `itemscope`s from fe_page.
@Xendiadyon can you test in one of your pages if the changes from this pull request fix the issue?
=> [RFC] Fix breadcrumb schema

src/Resources/contao/controllers/FrontendIndex.php
When you don't have an url suffix configured or it does not start by a `.`, the current regex does not match and thus the 404 page is not shown but instead the content of the page is loaded.
Steps to reproduce:
1. Configure `urlSuffix` to be an empty string `''`.
2. Add some regular content page with the alias `foobar` and note your id (e.g. `42`).
3. Call `/42`.
Expected:
I expect to be redirected to the configured 404 page because the page id 42 has a configured alias `foobar`.
What happens:
I can see the content of page ID `42`.
=> Fixed numeric aliases 404 handling

src/Resources/contao/library/Contao/Controller.php
This would be very helpful to use `Controller::addImageToTemplate()` for image sizes that are not stored in the database but are dynamically generated:
```php
\Controller::addImageToTemplate($template, ['singleSRC' => $path, 'size' => new PictureConfiguration(…)]);
```
=> [RFC] Support PictureConfigurationInterface as size parameter in Controller::addImageToTemplate()

src/ContaoCoreBundle.php, tests/ContaoCoreBundleTest.php
The changes in https://github.com/symfony/symfony/pull/27272 broke our support for doctrine migrations support.
=> Fixed DoctrineMigrationsPass not working with latest Symfony 3.4+

src/Resources/contao/dca/tl_page.php, src/Resources/contao/languages/en/tl_page.xlf
Now that Contao 4.6 supports cache tagging and invalidation by cache tags, we can increase the caching settings. This is especially true for the reverse proxy cache. Not sure if we also want to allow it for the `clientCache`. I haven't added this because I think a client should probably get a new response every month.
This is an intermediary step. The ultimate goal for Contao would be to disable the settings for the server cache entirely and always cache forever (aka 1 year) on the reverse proxy. Developers should actively tag responses and invalidate the cache entries when something happens in the back end so that a user doesn't need to care about that anymore but always gets maximum performance 😄
=> Add longer cache durations

src/Controller/AbstractFragmentController.php, src/Controller/ContentElement/AbstractContentElementController.php, src/Controller/FrontendModule/AbstractFrontendModuleController.php, tests/Controller/ContentElement/ContentElementControllerTest.php, tests/Controller/FrontendModule/FrontendModuleControllerTest.php
Added support for automatically tagging the elements created using the new abstract controllers. That was still missing 😄
=> Cache tags for new abstract controllers

src/Resources/contao/classes/RebuildIndex.php
If you try to access the Maintenance backend module as a non-admin which has access to multiple member groups, you will run into the SQL query error:
```
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT id, username FROM tl_member WHERE (GROUPS LIKE '%"3"%' OR1"%' OR4"%') AND disable!='1' AND (start='' OR start<='1531467943') AND (stop='' OR stop>'1531468003') ORDER BY username':
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OR1"%' OR4"%') AND disable!='1' AND (start='' OR start<='1531467943') AND (stop=' at line 1
```
This query is executed to fetch the available members that can be selected to …
=> Fixed the SQL query error when fetching members of multiple groups for search index rebuild

composer.json, src/Resources/contao/library/Contao/Search.php, src/Resources/contao/modules/ModuleSearch.php
As discussed in contao/core#2769.
This is a work in progress.
One problem I encountered is that it is currently possible to search in pages with different languages but we have to know the language in advance to know how to split the serch term. How should we do that?
=> [RFC] Use the Intl extension to split words

src/DependencyInjection/Compiler/AddResourcesPathsPass.php, tests/DependencyInjection/Compiler/AddResourcesPathsPassTest.php
Using Symfony Flex you do not have an AppBundle anymore. Therefore it is impossible to load (for example) templates from `src/Resource/contao`. These changes will add the `src/Resource/contao` directory hard-coded to the `AddResourcePathsPass`, like `app/Resource/contao` is already.
=> [RFC] Include the src/Resource/contao in contao.resource_pathes

src/Resources/contao/classes/DataContainer.php, src/Resources/contao/drivers/DC_Table.php
This is because a new entry (or an unpublished entry) might have not been shown and thus not tagged in the FE. We need to invalidate the direct parent to ensure these entries appear after changing them.
=> Delete parent tag on create and edit

README.md
This is an overhaul of the installation process documentation in the `README.md` file.
There is a few things this documentation relies on:
If you try this with a bare bone Symfony  (`composer create-project symfony/website-skeleton`) you will run run into an error, as the `json_manifest_file` does not yet exist.
Be sure to disable the manifest file in `config/assets.yaml`, as you won't be able to run `yarn run encore dev` without adding at least one asset file. But you'd need the manifest file in order to run the `asset()` calls in the error template of Contao.
I'm pretty sure this edge case is out of scope of this documentation, that's why I left it out.
=> [RFC] Documented the installation process for Symfony Flex
